In [38]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

### 문자열 함수.str

In [40]:
# 문자열함수 str함수 - startswith:'강'으로 시작하는 문자열
# startswith, endswith,contains,lower,upper, capitalize


# df[df['이름'].str.startswith('강')]
# df.loc[df['이름'].str.startswith('강')]

# contains : 포함되어 있는. ~은 not
# df[df['이름'].str.contains('원')]
# df[~df['이름'].str.contains('원')] # ~을 not

# lower,upper,capitalize
df['SW특기'].str.lower() # 소문자
df['SW특기'].str.upper() # 대문자
df['SW특기'].str.capitalize() # 첫 글자만 대문자
df[df['SW특기'].str.startswith('J')] #J로 시작하는 것

#isin : 여러개 검색 ['python','java']
# langs = ['python','java']
# #SW특기 값 소문자로 변경후 리스트 검색
# df[df['SW특기'].str.lower().isin(langs)] # 안의 것을 소문자로 다 바꿔주고 langs의 것들을 찾아달라는 말

#
df['SW특기'].str.contains('Java',na=False) # na = False :NaN 데이터 출력하지 않음
df['SW특기'].str.contains('Java',na=True) # na = True :NaN 데이터 출력
df[df['SW특기'].str.lower().str.contains('java',na=True)] # 소문자로 변경후 검색
# df['SW특기']

# unique 중복제거
df['학교'].unique()

<StringArray>
['구로고', '디지털고']
Length: 2, dtype: str

In [ ]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
# 1개일때 str없이 사용, 여러개일때 str을 입력후 사용
# df.iloc[0,2] = df.iloc[0,2].replace(',',"") # 천단위 표시 제거후 다시 저장
# df.iloc[0,2]
# 1개는 바꿔도 큰 의미가 없음 전체를 바꿔야함.
# int(df.iloc[0,2].replace(',',""))
df['총 인구수']=df['총 인구수'].str.replace(',',"").astype(int)
df['총 인구수']

c:\pythin313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0     51159889
1      9323492
2      3251625
3      2357040
4      3041215
5      1398538
6      1440682
7      1093317
8       392154
9     13715016
10     1510181
11     1591815
12     2136299
13     1729337
14     1782183
15     2516753
16     3214016
17      666226
Name: 총 인구수, dtype: int64

In [ ]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [36]:
# df = pd.read_excel('file/students.xlsx',index_col='번호')
# df[df['이름'].str.startswith('E')]

           이름   학교  학년    키  국어  영어  수학        SW특기
번호
1     Eadmund  신림고   2  171  56  92  60           c
20     Emelia  신림고   1  199  85  27  31  Javascript
21  Evangelia  신림고   2  190  51  71  83      PYTHON
55   Emmanuel  구로고   2  191  63  27  83        JAVA
88      Emile  신림고   2  199  83  26  68      PYTHON

In [ ]:
# df = pd.read_excel('file/students.xlsx',index_col='번호')
# # s가 있는 이름을 모두 출력, 대소문자 모두
# # df[df['이름'].str.contains('s','S')]
# # df['학교'] = df['학교'].str.replace('고등학교','고교')
# df['학교'] = df['학교'] + '등학교'
# df['학교']

번호
1       신림고등학교
2       구로고등학교
3       구로고등학교
4       구로고등학교
5      디지털고등학교
        ...
96      신림고등학교
97      구로고등학교
98      신림고등학교
99      구로고등학교
100    디지털고등학교
Name: 학교, Length: 100, dtype: str

In [89]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
# SW특기 java,c
langs = 'java','c'
# df[df['SW특기'].str.lower().isin(langs)]
df[df['SW특기'].str.lower().str.contains('java')]

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
54          Ula   신림고   3  168  80  59  85        java
55     Emmanuel   구로고   2  191  63  27  83        JAVA
56        Valle   신림고   3  167  68  83  52        java
60      Malynda  디지털고   1  178  57  79  72        java
65         Kiri   신림고   3  178  64  83  68        JAVA
66       Joanie   신림고   1  200  75  24  85        java
68        Tresa   구로고   2  166  58  37  70        java
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
82       Jamill   구로고   2  182  98   8  60        java
84          Ola  디지털고   3  170  84  77  77  Javascript
89       Norris  디지털고   3  174  68   9  51        java
91       Marika   신림고   2  189  89  22  32  Javascript
94         Kaja   신림고   1  202  53  44  78        java
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA