In [75]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
#컬럼선택 : df[컬럼], 2개이상[[]]리스트로 추가
df[['이름','학교','키']]
df.columns # 컬럼전체출력
df.columns[0] # 첫번쨰
df.columns[1] # 두번째
df.columns[-1] # 마지막 컬럼명을 출력
df['SW특기'] # 마지막 컬럼을 출력
df[df.columns[-1]] # 위 두개를 합쳐서 사용가능.
df[['이름','학교']]
df[df.columns[[0,3,-1]]] # 컬럼명을 여러개 사용해서 출력

SyntaxError: invalid syntax (1520657996.py, line 10)

In [ ]:
#df[컬럼명만 들어갈수있음]
df['이름'] 

# columns에 대한 슬라이싱
df[df.columns[[0,3,-1]]] # 컬럼 슬라이싱
df[df.columns[1:4]] # 컬럼 슬라이싱
df.columns[1:4] # 컬럼명

Index(['학교', '키', '국어'], dtype='str')

In [40]:
# rows에 대한 슬라이싱
df[['이름','학교','SW특기']][2:]
df['이름'][:3]
df[0:3]
df.iloc[[0,1,2,3]]
df.iloc[0:3]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [8]:
df = pd.read_csv('file/drinks.csv')

In [ ]:
df['continent']    # 마지막 컬럼 출력
df[df.columns[-1]] # 마지막 컬럼 출력

0      AS
1      EU
2      AF
3      EU
4      AF
       ..
188    SA
189    AS
190    AS
191    AF
192    AF
Name: continent, Length: 193, dtype: str

In [74]:
# df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols='C:D,H:I')
# df
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
df[df.columns[[2,3,7,8]]]

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

         총 인구수     연령구간인구수     30~39세     40~49세
0   51,159,889  51,159,889  6,649,487  7,627,071
1    9,323,492   9,323,492  1,453,915  1,370,576
2    3,251,625   3,251,625    388,293    464,061
3    2,357,040   2,357,040    284,076    338,976
4    3,041,215   3,041,215    427,940    474,175
5    1,398,538   1,398,538    173,489    215,553
6    1,440,682   1,440,682    193,281    210,477
7    1,093,317   1,093,317    136,397    170,157
8      392,154     392,154     58,404     76,817
9   13,715,016  13,715,016  1,915,357  2,191,701
10   1,510,181   1,510,181    158,114    196,699
11   1,591,815   1,591,815    190,906    222,510
12   2,136,299   2,136,299    252,062    315,039
13   1,729,337   1,729,337    172,529    229,830
14   1,782,183   1,782,183    169,648    229,537
15   2,516,753   2,516,753    253,958    337,104
16   3,214,016   3,214,016    343,941    480,612
17     666,226     666,226     77,177    103,247

In [ ]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols='C:D,H:I')
# str타입 replace함수 : 천단위 쉼표 삭제
# 타입변경 : astype(int)-(float)(str)등 사용하여 타입을 변경
df[:1]['총 인구수'].str.replace(',','').astype(int)

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0    51159889
Name: 총 인구수, dtype: int64

In [81]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,index_col='행정기관')

df.columns
df.index[0]
df.loc['전국  ']

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

행정기관코드                 0
총 인구수         51,159,889
연령구간인구수       51,159,889
0~9세           3,024,945
10~19세         4,630,054
                 ...
60~69세.17      4,015,237
70~79세.17      2,434,888
80~89세.17      1,334,492
90~99세.17        276,634
100세 이상.17         7,285
Name: 전국  , Length: 235, dtype: object

In [70]:
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
df.set_index('영화',inplace=True)
df.to_excel('file/screen1.xlsx')

In [71]:
df = pd.read_excel('file/screen1.xlsx',index_col='영화')
df

           개봉 연도  관객 수    평점
영화
명량          2014  1761  8.88
극한직업        2019  1626  9.20
신과함께-죄와 벌   2017  1441  8.73
국제시장        2014  1426  9.16
괴물          2006  1301  8.62
도둑들         2012  1298  7.64
7번방의 선물     2013  1281  8.83
암살          2015  1270  9.10