In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('file/합계출산율_2026.xlsx',skiprows=28,nrows=2)
# df.columns
df.set_index('Unnamed: 0',inplace=True)
# df.index.name='제목'
# df.columns
# df.index
# df.index.values # index 안에 유니코드까지 출력이 가능
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Unnamed: 0,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [ ]:
# df.loc('출생아 수')

df.index.values[0]
df.index.values[1]

'출생아\xa0수'

In [5]:
# index의 이름변경
df.rename(index={'출생아\xa0수':'출생아수'},inplace=True)
df.rename(index={'합계\xa0출산율':'합계출산율'},inplace=True)
df

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Unnamed: 0,,,,,,,,,,
출생아수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [10]:
df.index.values[0]
df.loc['출생아수']

2016    406.2
2017    357.8
2018    326.8
2019    302.7
2020    272.3
2021    260.6
2022    249.2
2023    230.0
2024    238.3
2025    254.3
Name: 출생아수, dtype: float64