In [2]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# 조건 : 필터 적용해서 조건 적용
df['키']>=185 # True, False 형태로 출력
df[df['키']>=185] 

filt = df['키']>=185 # 변수로 만들어서 넣어도 됨.
df[filt]
# df[-filt] # ~not적용
# df[-filt]['키']

# 위에를 풀어 쓰면 이렇게 사용
df2 = df[filt]
df3 = df2[['이름','키','국어']]
df3

       이름    키   국어
지원번호
1번    강나래  197   90
4번    김수찬  187   40
5번    김재욱  188   15
6번    박동현  202   80
7번    박혜정  188   55
8번    승근열  190  100

In [ ]:
df3=df2[df2['국어']>=80]
df[(df['키']>=185) & (df['국어']>=90)] # &사용 and는 안됨
df[(df['키']>=185) | (df['국어']>=90)] # or,|,|| (|==\+shift)

SyntaxError: invalid syntax (572758863.py, line 2)

In [28]:
df.loc[(df['키']>=185)&(df['국어']>=90),['수학']]

       수학
지원번호
1번    100
8번     90